# Generated by Django 4.1.3 on 2022-11-20 15:59

from django.db import migrations, models
import travel_frame.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('travel_photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelphoto',
            name='photo',
            field=models.ImageField(upload_to='travel_photos/', validators=[travel_frame.core.validators.validate_image]),
        ),
    ]
