# Generated by Django 4.1.3 on 2022-11-22 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_photos', '0003_travelphoto_tagged_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelphoto',
            name='tagged_users',
        ),
        migrations.AddField(
            model_name='travelphoto',
            name='tagged_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
