# Generated by Django 4.1.3 on 2022-11-20 15:50

from django.db import migrations, models
import travel_frame.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[travel_frame.core.validators.validate_only_letters])),
                ('continent', models.CharField(choices=[('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Asia', 'Asia'), ('Africa', 'Africa'), ('Australia and Oceania', 'Australia and Oceania'), ('Antarctica', 'Antarctica')], max_length=21)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('flag', models.ImageField(blank=True, upload_to='countries_flags/', validators=[travel_frame.core.validators.validate_image])),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
